name: CI

on:
  push:
    branches:
      - main
      - 'v*'
  pull_request: {}

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: 12.x
          yarn-version: 1.x

      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn lint:js
      - run: yarn build
      - run: yarn test:types

  package-tests:
    name: Package Tests
    runs-on: ubuntu-latest

    env:
      CI: 'true'

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: 12.x
          yarn-version: 1.x
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn build
      - name: Test
        run: yarn workspace glimmer-apollo run test

  glimmerx-tests:
    name: Glimmerx Tests
    runs-on: ubuntu-latest

    env:
      CI: 'true'

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: 12.x
          yarn-version: 1.x
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn build
      - name: Test
        run: yarn workspace test-glimmerx run test
