name: CI

on:
  push:
    branches:
      - main
      - 'v*'
  pull_request: {}

env:
  CI: 'true'

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: 12.x
          yarn-version: 1.x

      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn lint:js
      - run: yarn build
      - run: yarn test:types

  package-tests:
    name: Glimmer Apollo Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: 12.x
          yarn-version: 1.x
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn build
      - name: Test Glimmer Apollo
        run: yarn workspace glimmer-apollo run test
      - name: Test App
        run: yarn workspace test-app run test

  examples-glimmerx:
    name: GlimmerX Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
        with:
          node-version: 12.x
          yarn-version: 1.x
      - run: yarn install --frozen-lockfile --non-interactive
      - run: yarn build
      - name: Test
        run: yarn workspace glimmerx run test
